name: Deploy Node.js App to Ubuntu VPS

on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  deploy:
    if: github.event_name == 'push' || (github.event.pull_request.merged == true)
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Install SSH Client
      run: sudo apt-get install -y sshpass

    - name: Deploy over SSH
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      uses: appleboy/ssh-action@v0.1.10
      with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd /home/optics/opticcsapp
            git pull origin main
            npm install
            npx prisma generate
            npm run build
            pm2 restart optics
      


